NLog/NLog.Extensions.Logging

src/NLog.Framework.logging/AspNetExtensions.cs

Fixes ConfigureNLog method which takes IHostingEnvironment as parameter.
Because NLogLoggerProvider implements IDisposable, modified "AddNlog" method to dispose it.

AspNetExtensions: dispose in AddNLog

---

src/NLog.Extensions.Logging/AspNetExtensions.cs
src/NLog.Extensions.Logging/project.json

Fixes https://github.com/NLog/NLog/issues/1512
```c#
//typeof logger: NLog.Logger
Logger.Info("Index page says hello");
```
this wasn't working:
```c#
//typeof _logger: Microsoft.Extensions.Logging.ILogger
_logger.LogInformation("info 2 with DI");
```
Example log with fix:
```
Microsoft.AspNetCore.Hosting.Internal.HostingLoggerExtensions.RequestStarting | Request starting HTTP/1.1 GET http://localhost:59915/  
Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke | The request path / does not match a supported file type
Microsoft.AspNetCore.Routing.Logging.TreeRouterLoggerExtensions.MatchedRoute | Request successfully matched the route with name 'default' and template '{controller=Home}/{action=Index}/{id?}'.
Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeAsync | …
```

Fix ${callsite} when using DI logger

---

src/NLog.Extensions.Logging/AspNetExtensions.cs
src/NLog.Extensions.Logging/NLogLogger.cs
src/NLog.Extensions.Logging/NLogLoggerProvider.cs
src/NLog.Extensions.Logging/NLogProviderOptions.cs
src/NLog.Extensions.Logging/project.json

Fixes https://github.com/NLog/NLog.Extensions.Logging/issues/64
Usage:
```C#
loggerFactory.AddNLog(new NLogProviderOptions {EventIdSeparator = "_"});
```

Added NLog provider options - EventIdSeparator

---

global.json
src/NLog.Extensions.Logging/ConfigureExtensions.cs
src/NLog.Extensions.Logging/project.json

fixes https://github.com/NLog/NLog.Extensions.Logging/issues/25, 
see also https://github.com/NLog/NLog.Extensions.Logging/issues/76
- remove ASP.NET helper
- rename AspNetExtensions => ConfigureExtensions
- ConfigureNLog now as extention on `ILoggerFactory` instead of `IHostingEnvironment`
- update SKD, NLog & tags
see also https://github.com/NLog/NLog.Web/pull/88

remove ASP.NET dependency

---

src/NLog.Extensions.Logging/project.json

Because beta5 has known issues with archiving. See #100

Update dependencies (NLog 5 - beta6)

---

src/NLog.Extensions.Logging/NLogLogger.cs
src/NLog.Extensions.Logging/NLogProviderOptions.cs

Following memory optimizations:
- Skip four property-name-string-allocations for every LogEvent
- Skip boxing of default EventId-struct for every LogEvent
- Skip boxing of zero-EventId-value for every LogEvent
Added new NLogProviderOptions.IgnoreEmptyEventId (default = false), so it skips LogEventInfo.Properties-Dictionary-allocation for every LogEvent (when no EventId)

Minimize string-allocations when adding EventId-properties

---

src/NLog.Extensions.Logging/NLog.Extensions.Logging.csproj
src/NLog.Extensions.Logging/NLogLogger.cs

In order to be use properly from asp.net core we need to use NestedDiagnosticsLogicalContext fro BeginScope method.
-----
upgrade NLog version
switch from NestedDiagnosticsContext to NestedDiagnosticsLogicalContext
fixes https://github.com/NLog/NLog.Extensions.Logging/issues/10

switch from NestedDiagnosticsContext to NestedDiagnosticsLogicalContext

---

src/NLog.Extensions.Logging/NLog.Extensions.Logging.csproj
src/NLog.Extensions.Logging/NLogLogger.cs
src/NLog.Extensions.Logging/NLogMessageParameterList.cs
src/NLog.Extensions.Logging/NLogProviderOptions.cs
test/LoggerTests.cs
test/NLog.Extensions.Logging.Tests.csproj
test/nlog.config

Extracted from Microsoft FormattedLogValues. Allowing NLog to support structured logging using the Microsoft-parser-engine. Resolves #116
P.S. Funny detail discovered while digging around in the Microsoft-machine-room (Notice the static ConcurrentDictionary and limit of 1024)
https://github.com/aspnet/Logging/blob/cc503aaed0b9fb3e93345b28629e80581337d3c1/src/Microsoft.Extensions.Logging.Abstractions/Internal/FormattedLogValues.cs
P.P.S. Surprised that they are not using the StringComparer.Ordinal for the ConcurrentDictionary

Capture structured logging parameter names

---

src/NLog.Extensions.Logging/NLogLogger.cs
src/NLog.Extensions.Logging/NLogProviderOptions.cs
test/LoggerTests.cs

CaptureMessageTemplate better matches the suggested ParseMessageTemplate-config-name.
See also https://github.com/NLog/NLog/issues/2347

MessageTemplate  - Structured logging parameters (Better option name)

---

src/NLog.Extensions.Logging/NLogLogger.cs
src/NLog.Extensions.Logging/NLogProviderOptions.cs
test/LoggerTests.cs
test/nlog.config

Using ILogger-state and ILogger-scope. Resolves https://github.com/NLog/NLog/issues/1366

MessageProperties - Allow capture of message properties (CaptureMessageProperties option)

---

src/NLog.Extensions.Logging/NLogProviderOptions.cs
test/LoggerTests.cs

IgnoreEmptyEventId = true and default EventIdSeparator to underscore.
Resolves #150  + #149

NLogProviderOptions: added IgnoreEmptyEventId, set default EventIdSeparator to underscore.

---

src/NLog.Extensions.Logging/NLog.Extensions.Logging.csproj
test/LoggerTests.cs
test/NLog.Extensions.Logging.Tests.csproj

And fixed unit tests
Enables NetCoreApp1.1 users to access the latest NLog 4.5 features.

Introduced NetStandard1.5 by updating to NLog 4.5-beta07

---

NLog.Extensions.Logging.sln
examples/NetCore2/ConsoleExample/ConsoleExample.csproj
examples/NetCore2/ConsoleExample/NLog.xsd
examples/NetCore2/ConsoleExample/Program.cs
examples/NetCore2/ConsoleExample/nlog.config

fixes https://github.com/NLog/NLog.Extensions.Logging/issues/131

Added Console Example

---

examples/NetCore2/ConsoleExample/ConsoleExample.csproj
examples/NetCore2/ConsoleExample/Program.cs

Also add a mandatory dep
Related to #166 and #143

Update NetCore2 ConsoleExample to include the minimumlevel.

---

examples/NetCore2/ConsoleExample/ConsoleExample.csproj
src/NLog.Extensions.Logging/ConfigureExtensions.cs
src/NLog.Extensions.Logging/NLog.Extensions.Logging.csproj
src/NLog.Extensions.Logging/NLogLogger.cs
src/NLog.Extensions.Logging/NLogMessageParameterList.cs
test/NLog.Extensions.Logging.Tests.csproj

Implement .NET standard 2 features for .NET 4.6.1, MessageTemplates for .NET standard 1.5 + NET 4.51, updated dependencies
Force NLog ver. 4.5-rc01 for all (except NetStandard1.3) 
Resolves https://github.com/NLog/NLog.Web/issues/208 (Maybe wait with this until NLog 4.5 RTM)

Implement .NET standard 2 features for .NET 4.6.1 + update dependencies + messagetemplates

---

src/NLog.Extensions.Logging/NLogLogger.cs
src/NLog.Extensions.Logging/NLogMessageParameterList.cs

fixes #175 
+ removed code dupl
@snakefoot your opinion on this please. I'm now checking multiple times the first parameter char. doubting about that (performance reasons)

Fix: Captured parameter name has unwanted @ or $ prefix

---

src/NLog.Extensions.Logging/NLogMessageParameterList.cs

Make it easier to understand the validation of the input parameterList

NLogMessageParameterList - Refactor validation of parameterList

---

src/NLog.Extensions.Logging/NLog.Extensions.Logging.csproj
test/NLog.Extensions.Logging.Tests.csproj

Fixes https://github.com/NLog/NLog.Extensions.Logging/issues/179

Upgrade to NLog 4.5 rc2, remove nlog 5 reference, version to rc4

---

build.ps1
src/NLog.Extensions.Logging/NLog.Extensions.Logging.csproj

Prepare RC7

---

build.ps1
examples/NetCore2/ConsoleExample/Program.cs
examples/NetCore2/ConsoleExample/nlog.config
src/NLog.Extensions.Logging/Extensions/ConfigureExtensions.cs
src/NLog.Extensions.Logging/Logging/NLogLogger.cs
src/NLog.Extensions.Logging/NLog.Extensions.Logging.csproj
test/CustomLoggerCallSiteTest.cs
test/LoggerTests.cs
test/NLogTestBase.cs
test/Properties/AssemblyInfo-test.cs

Completed the callsite-fix, that started with https://github.com/NLog/NLog/pull/2609
Also made it easier to add new unit-test-classes, instead of all being based on the same NLog.config.

CallSite should recognize all Microsoft.Extensions.Logging.ILogger

---

src/NLog.Extensions.Logging/Logging/NLogLoggerProvider.cs

Added the Microsoft.Extensions.Logging.ProviderAliasAttribute to the NLogLoggerProvider to enable it to be used Logging Configuration instead of having to supply the full name of the provider class.

Add Alias attribute to NLogLoggerProvider

---

src/NLog.Extensions.Logging/Extensions/ConfigureExtensions.cs
src/NLog.Extensions.Logging/Logging/NLogLoggerProvider.cs

My take on solving https://github.com/NLog/NLog/issues/2647
Then remove the callsite-assembly-logic from NLog.Web, as it is now in "one" place.

Automatic loading of hidden assemblies for callsite logic in NetCore2

---

src/NLog.Extensions.Logging/Logging/NLogLogger.cs
test/LoggerTests.cs

Make BeginScope more user-friendly by accepting any type of KeyValuePair.
There is an overhead from lookup in ConcurrentDictionary and boxing, so maybe one should just write to the InternalLogger instead of doing reflection.

BeginScope accepts any type of KeyValuePair and Dictionary

---

src/NLog.Extensions.Logging/Logging/NLogLogger.cs

Added try-catch-logic to ensure BeginScope doesn't throw unexpectedly.

BeginScope should accept any type of KeyValuePair (Swallow exceptions)

---

examples/NetCore2/ConsoleExample/Program.cs
src/NLog.Extensions.Logging/Extensions/ConfigureExtensions.cs
src/NLog.Extensions.Logging/Logging/NLogBeginScopeParser.cs
src/NLog.Extensions.Logging/Logging/NLogLogger.cs
src/NLog.Extensions.Logging/Logging/NLogLoggerFactory.cs
src/NLog.Extensions.Logging/Logging/NLogLoggerProvider.cs
src/NLog.Extensions.Logging/Logging/NLogMessageParameterList.cs
src/NLog.Extensions.Logging/Logging/NLogProviderOptions.cs
src/NLog.Extensions.Logging/NLog.Extensions.Logging.csproj
test/CustomBeginScopeTest.cs
test/CustomLoggerPropertyTest.cs

Improves the support of custom objects together with BeginScope, when using AppDomains (Using CallContext that requires serializable objects)
Ex. ActionLogScope. Attempt to resolve https://github.com/NLog/NLog/issues/2812
Includes a small performance boost in handling of Microsofts internal `ActionLogScope` + `HostingLogScope` + `FormattedLogValue` by using IReadOnlyList in the fast-path of BeginScope. (Still supports Arrays and Lists), so it doesn't allocate yield-enumerator or uses keyvaluepair-property-extractor.
Includes a small performance boost by reusing a shared allocation of NLogBeginScopeParser (lives on the NLogLoggerProvider) for all NLogLogger-objects.
Includes a small performance boost in handling of log-message with no message-properties, by skipping allocation of …

BeginScope: support for non-serializable objects + performance improvement (20-50% cpu, 35% times less allocations)

---

src/NLog.Extensions.Logging/Logging/NLogBeginScopeParser.cs
src/NLog.Extensions.Logging/Logging/NLogLogger.cs
src/NLog.Extensions.Logging/Logging/NLogLoggerFactory.cs
src/NLog.Extensions.Logging/Logging/NLogLoggerProvider.cs
test/CustomBeginScopeTest.cs

Fixed bug introduced with #232

Fixed null-reference-exception when parsing empty scope-property collection

---

src/NLog.Extensions.Logging/Logging/NLogMessageParameterList.cs
test/NLog.Extensions.Logging.Tests/NLogMessageParameterListTests.cs

ref : System.ArgumentOutOfRangeException : Index was out of range. Must be non-negative and less than the size of the collection. Parameter name: index

Fixing bug throwing ArgumentOutOfRangeException if input is empty list

---

src/NLog.Extensions.Logging/Logging/NLogMessageParameterList.cs
test/NLog.Extensions.Logging.Tests/LoggerTests.cs

Throw FormatException when IndexOutOfRangeException caused by invalid parameters
See also #271

Handle IndexOutOfRangeException thrown by Microsoft.Extensions.Logging when using invalid format string

---

NLog.Extensions.Logging.sln
build.ps1
examples/NetCore2/ConsoleExample/ConsoleExample.csproj
examples/NetCore2/ConsoleExample/Program.cs
examples/NetCore2/ConsoleExample/appsettings.json
src/NLog.Extensions.Logging/Config/NLogLoggingConfiguration.cs
src/NLog.Extensions.Logging/Internal/StringExtensions.cs
src/NLog.Extensions.Logging/Logging/NLogBeginScopeParser.cs
src/NLog.Extensions.Logging/Logging/NLogLogger.cs
src/NLog.Extensions.Logging/Logging/NLogLoggerProvider.cs
src/NLog.Extensions.Logging/NLog.Extensions.Logging.csproj
src/NLog.Extensions.Logging/NLog.Extensions.Logging.csproj.DotSettings
test/NLog.Extensions.Logging.Tests/ConfigSettingLayoutRendererTests.cs
test/NLog.Extensions.Logging.Tests/NLog.Extensions.Logging.Tests.csproj
test/NLog.Extensions.Logging.Tests/NLogLoggingConfigurationTests.cs

Load NLog config from appsettings.json using NLogLoggingConfiguration
Loading configuration like this:
```c#
var config = new ConfigurationBuilder()
.SetBasePath(System.IO.Directory.GetCurrentDirectory())
.AddJsonFile("appsettings.json", optional: true, reloadOnChange: true)
.Build();
LogManager.Configuration = new NLogLoggingConfiguration(config.GetSection("NLog"));
```
Example JSON-config:
```json
{
"NLog": {
"internalLogLevel": "Info",
"internalLogFile": "c:/temp/console-example-internal.log",
"throwConfigExceptions": "True",
"targets": {
"console": {
"type": "Console",
"layout": "${longdate}|${level:uppercase=true}|${logger}|${message}${exception:format=tostring}"
},
"file": {
"type": "AsyncWrapper",
"target": {
"wrappedFile": {
"type": "File",
"fileName": …
```

Load JSON based NLog config (e.g. declared in appsettings.json) + BeginScopeParser performance improvements

---

CHANGELOG.MD
examples/NetCore2/ConsoleExample/Program.cs
src/NLog.Extensions.Logging/Config/NLogLoggingConfiguration.cs
test/NLog.Extensions.Logging.Tests/NLogLoggingConfigurationTests.cs

and default-target-parameters:
Example JSON-config:
```json
{
"NLog": {
"targets": {
"default-wrapper": {
"type": "AsyncWrapper",
"overflowAction": "Block"
},
"default-target-parameters": {
"console": {
"error": "true",
},
"file": {
"encoding": "utf-8",
},
},
"console": {
"type": "Console"
},
"debugLog": {
"type": "File",
"fileName": "c:/temp/console-debug.log"
},
"errorLog": {
"type": "File",
"fileName": "c:/temp/console-error.log"
}
},
"rules": [
{
"logger": "*",
"minLevel": "Trace",
"writeTo": "debugLog,Console"
},
{
"logger": "*",
"minLevel": "Error",
"writeTo": "errorLog"
}
]
}
}
```

NLogLoggingConfiguration - Added support for default-wrapper, default-target-parameter & autoReload

---

src/NLog.Extensions.Logging/Logging/NLogLoggerProvider.cs
src/NLog.Extensions.Logging/Logging/NLogProviderOptions.cs

Fixes https://github.com/NLog/NLog.Extensions.Logging/issues/313

Added NLogProviderOptions.ShutdownOnDispose

---

CHANGELOG.MD
build.ps1
src/NLog.Extensions.Hosting/NLog.Extensions.Hosting.csproj
src/NLog.Extensions.Logging/Config/NLogLoggingConfiguration.cs
src/NLog.Extensions.Logging/NLog.Extensions.Logging.csproj

See also: https://stackoverflow.com/questions/57485634/memory-leak-why-too-many-ichangetoken-objects

NLogLoggingConfiguration - Fix leak in RegisterChangeCallback

---

src/NLog.Extensions.Hosting/Extensions/ConfigureExtensions.cs
src/NLog.Extensions.Logging/Extensions/ConfigureExtensions.cs
test/NLog.Extensions.Hosting.Tests/ExtensionMethodTests.cs

Resolves #324 for ILoggingBuilder. But will NOT help #254 for `ILoggerFactory`.
Fixes lifetime issue found in https://github.com/NLog/NLog/issues/3284 where calling `ILoggingBuilder.AddNLog`  caused NLogLoggingProvider not being disposed correctly on application shutdown (No flush and shutdown).

 ILoggingBuilder AddNLog extension method with correct dispose and no double logging

---

src/NLog.Extensions.Logging/Logging/NLogLoggerFactory.cs
src/NLog.Extensions.Logging/Logging/NLogLoggerProvider.cs
test/NLog.Extensions.Logging.Tests/CustomBeginScopeTest.cs
test/NLog.Extensions.Logging.Tests/CustomLoggerCallSiteTest.cs
test/NLog.Extensions.Logging.Tests/CustomLoggerPropertyTest.cs
test/NLog.Extensions.Logging.Tests/LoggerTests.cs
test/NLog.Extensions.Logging.Tests/Logging/NLogLoggerFactoryTests.cs
test/NLog.Extensions.Logging.Tests/Logging/NLogLoggerProviderTests.cs
test/NLog.Extensions.Logging.Tests/NLogMessageParameterListTests.cs
test/NLog.Extensions.Logging.Tests/NLogTestBase.cs

Trying to resolve #326 by cleaning up tests that depend on LogManager and InternalLogger.

NLog.Extension.Logging.Tests - Stop using static LogManager

---

src/NLog.Extensions.Logging/Logging/NLogBeginScopeParser.cs
src/NLog.Extensions.Logging/Logging/NLogLogger.cs
src/NLog.Extensions.Logging/Logging/NLogMessageParameterList.cs
test/NLog.Extensions.Logging.Tests/NLogMessageParameterListTests.cs

And micro-optimization for comparison against OriginalFormatPropertyName (skip null-check by using Equals for OriginalFormatPropertyName-object)

NLogMessageParameterList - Reduce code complexity for IsValidParameterList

---

CHANGELOG.MD
build.ps1
src/NLog.Extensions.Logging/Extensions/ConfigureExtensions.cs
src/NLog.Extensions.Logging/NLog.Extensions.Logging.csproj
test/NLog.Extensions.Logging.Tests/Extensions/ConfigureExtensionsTests.cs

ILoggerFactory is obsolete in .NET Core 3. Instead use ILoggingBuilder.AddNLog

---

src/NLog.Extensions.Hosting/Extensions/ConfigureExtensions.cs
src/NLog.Extensions.Logging/Extensions/ConfigureExtensions.cs
test/NLog.Extensions.Logging.Tests/Extensions/ConfigureExtensionsTests.cs

Will also allow AddNLog to automatically register `ConfigSettingLayoutRenderer.DefaultConfiguration` by extracting `IConfiguration` from `ServiceProvider` (When not provided directly)

Introduce AddNLog with NLog-config parameter

---

src/NLog.Extensions.Hosting/Extensions/ConfigureExtensions.cs

Fixed bug introduced with IServiceCollection.Replace. Instead use TryAddEnumerable
Resolves #348 by fixing bug introduced with #344.
Same as https://github.com/NLog/NLog.Web/pull/485

Fixed conflict issue between UseNLog and default log providers

---

appveyor.yml
src/NLog.Extensions.Logging/LayoutRenderers/ActivityTraceLayoutRenderer.cs
src/NLog.Extensions.Logging/LayoutRenderers/ActivityTraceProperty.cs
test/NLog.Extensions.Logging.Tests/ActivityTraceLayoutRendererTests.cs

Resolves #358 for NetCoreApp3.
`System.Diagnostics.Activity.Current` also exists in NetCoreApp2 and NetCoreApp21 and NetCoreApp22. But lets see what happens with NetCoreApp3.

ActivityTraceLayoutRenderer - Renders System.Diagnostics.Activity.Current properties

---

src/NLog.Extensions.Logging/Logging/NLogLogger.cs
src/NLog.Extensions.Logging/Logging/NLogLoggerFactory.cs
test/NLog.Extensions.Logging.Tests/Logging/NLogLoggerFactoryTests.cs

See also: 
https://github.com/aspnet/Extensions/blob/03ca0e1aa41c55a94e6c04f0c1fa803986fe9e64/src/Logging/Logging/src/LoggerFactory.cs#L99

NLogLoggerFactory - Emulate Microsoft LoggerFactory by returning same ILogger instance

---

examples/NetCore2/HostingExample/Program.cs

Disable MEL-Filtering by default, and instead rely on NLog-Filter-Rules.

NLog Hosting Sample include ConfigureLogging with SetMinimumLevel

---

src/NLog.Extensions.Logging/Extensions/ConfigureExtensions.cs
test/NLog.Extensions.Logging.Tests/Extensions/ConfigureExtensionsTests.cs

Resolves #391
Added overload of `AddNLog` to accept both `NLogProviderOptions` and `LoggingConfiguration` and corresponding test.

AddNLog overload with NLogProviderOptions and LoggingConfiguration

---

src/NLog.Extensions.Logging/Extensions/ConfigureExtensions.cs

Improve AddNLog with LoggingConfiguration to handle custom LogFactory

---

examples/NetCore2/ConsoleExampleJsonConfig/Program.cs
src/NLog.Extensions.Logging/Config/ISetupLoggerProviderBuilder.cs
src/NLog.Extensions.Logging/Config/SetupBuilderExtensions.cs
src/NLog.Extensions.Logging/Config/SetupLoggerProviderBuilderExtensions.cs
src/NLog.Extensions.Logging/NLog.Extensions.Logging.csproj
test/NLog.Extensions.Logging.Tests/NLogLoggingConfigurationTests.cs

Example of how it is used:
```c#
LogManager.Setup()
.SetupExtensions(s => s.AutoLoadAssemblies(false))
.SetupExtensionLogging(s => s.LoadNLogLoggingConfiguration(config));
```

Introduced SetupExtensionLogging extension method for LogFactory.Setup

---

src/NLog.Extensions.Logging/Config/NLogLoggingConfiguration.cs
test/NLog.Extensions.Logging.Tests/NLogLoggingConfigurationTests.cs

Spaces are automatically ignore in xml:
```xml
<target type="file"    fileName="hello.txt" />
```
But not with json:
```json
"file" {
"  fileName": "hello.txt"
}
```
See also: https://stackoverflow.com/a/61549064/193178

Reading JSON config - Trim keys as Json allows spaces in keys

---

examples/NetCore2/ConsoleExampleJsonConfig/Program.cs
src/NLog.Extensions.Logging/Config/SetupBuilderExtensions.cs
test/NLog.Extensions.Logging.Tests/NLogLoggingConfigurationTests.cs

Adjusted #412
Updated example:
```c#
LogManager.Setup()
.SetupExtensions(s => s.AutoLoadAssemblies(false))
.LoadConfigurationFromSection(config);
```
Matches: https://github.com/NLog/NLog/pull/3871 for NLog 4.7.1
Allow override of `configSection` to support `"AzureFunctionsJobHost:NLog"`

Renaming LoadNLogConfigFromSection  to LoadConfigurationFromSection

---

src/NLog.Extensions.Logging/Config/SetupExtensionsBuilderExtensions.cs

Fixing copy-paste code from NLog.Web. Was surprised that NLog.Extension.Logging was released before NLog 4.7.1 (Would have liked to be testing them all together first)

LogFactory.Setup - Make RegisterConfigSettings public

---

src/NLog.Extensions.Logging/Targets/MicrosoftILoggerTarget.cs
test/NLog.Extensions.Logging.Tests/MicrosoftILoggerTargetTests.cs

Then output from NLog Loggers can be redirected to match function-name:
```c#
//setup target to forward NLog logs to ILogger
//NOTE: string passed to CreateLogger must match "function.<function name>" or logs will not show in Log Stream
var msLoggerFactory = serviceProvider.GetService<ILoggerFactory>();
var msLogger = msLoggerFactory.CreateLogger("Function.TestLog");
var nLogToMsLogTarget = new MicrosoftILoggerTarget(msLogger) { LoggerName = "${mdlc:FunctionName}" };
```
And one can then forward the ILogger-name to NLog like this:
```c#
[FunctionName("TestLog")]
public static async Task<IActionResult> TestLog([HttpTrigger(AuthorizationLevel.Function, "get", "post", Route = null)]
HttpRequest req, ILogger log)
{
using (NLog.MappedDiagnosticsLogicalContext.SetScoped("FunctionName", …
```

MicrosoftILoggerTarget - Add support for override LoggerName when using ILoggerFactory

---

src/NLog.Extensions.Hosting/Extensions/ConfigureExtensions.cs
src/NLog.Extensions.Logging/Logging/NLogLoggerProvider.cs

NetStandard2 is capable of hiding the LoggerFactory-assembly, and the [Microsoft.Extensions.Logging.Filter](https://www.nuget.org/packages/Microsoft.Extensions.Logging.Filter/) only works for NetCore1.
When calling UseNLog or AddNLogWeb then NLog.Web.AspNetCore will ensure to "hide" itself.

Remove startup overhead caused by enumerating all assemblies for callsite logic

---

src/NLog.Extensions.Logging/LayoutRenderers/MicrosoftConsoleLayoutRenderer.cs
test/NLog.Extensions.Logging.Tests/MicrosoftConsoleLayoutRendererTest.cs

Resolves #489 so you can do this:
```xml
<nlog>
<targets>
<target name="lifetimeConsole" xsi:type="Console" layout="${MicrosoftConsoleLayout}"  />
</targets>
<rules>
<logger name="Microsoft.Hosting.Lifetime" level="Info" writeTo="lifetimeConsole" final="true" /> 
</rules>
</nlog>
```

MicrosoftConsoleLayoutRenderer - For Hosting Lifetime Startup Messages

---

appveyor.yml
run-sonar.ps1

msbuild-sonarqube-runner is deprecated
trying to fix #492

Fix SonarQube Scanning

---

src/NLog.Extensions.Logging/Config/NLogLoggingConfiguration.cs
src/NLog.Extensions.Logging/Config/SetupBuilderExtensions.cs
test/NLog.Extensions.Logging.Tests/NLogLoggingConfigurationTests.cs

Support TargetDefaultWrapper and TargetDefaultParameters

---

src/NLog.Extensions.Logging/Logging/NLogLogger.cs
src/NLog.Extensions.Logging/Logging/NLogProviderOptions.cs

When using `NLogProviderOptions.RemoveLoggerFactoryFilter = true`, then Microsoft LoggerFactory will arrive with all LogEvents on all LogLevels (No longer "protected" by Microsoft Filtering-logic)
Reduced to single switch from Microsoft LogLevel to NLog Logger-IsEnabled. For faster discarding of Debug / Trace-vents.
Instead of making 2 switches:
- Microsoft LogLevel -> NLog LogLevel
- NLog LogLevel -> NLog Logger-IsEnabled.

NLogLogger - Faster checking if LogLevel IsEnabled

---

test/NLog.Extensions.Hosting.Tests/NLog.Extensions.Hosting.Tests.csproj
test/NLog.Extensions.Logging.Tests/NLog.Extensions.Logging.Tests.csproj

Disable ImplicitNuGetFallbackFolder for tests - fixes NU3005 on AppVeyor

---

src/NLog.Extensions.Hosting/Extensions/ConfigureExtensions.cs
src/NLog.Extensions.Logging/Extensions/ConfigureExtensions.cs

Better experience out-of-the-box when running on Azure Functions with special application-lifetime-events.

NLogLoggerProvider - Always load from appsettings when possible

---

src/NLog.Extensions.Logging/Config/NLogLoggingConfiguration.cs
test/NLog.Extensions.Logging.Tests/NLogLoggingConfigurationTests.cs

Fix NLogLoggingConfiguration to handle throwConfigExceptions with NLog 5.0

---

src/NLog.Extensions.Hosting/Extensions/ConfigureExtensions.cs
src/NLog.Extensions.Logging/Extensions/ConfigureExtensions.cs
src/NLog.Extensions.Logging/LayoutRenderers/ConfigSettingLayoutRenderer.cs
src/NLog.Extensions.Logging/LayoutRenderers/MicrosoftConsoleLayoutRenderer.cs
src/NLog.Extensions.Logging/Logging/NLogProviderOptions.cs
src/NLog.Extensions.Logging/NLog.Extensions.Logging.csproj
test/NLog.Extensions.Hosting.Tests/ExtensionMethodTests.cs
test/NLog.Extensions.Logging.Tests/CustomBeginScopeTest.cs

NLogProviderOptions with support for RegisterServiceProvider

---

src/NLog.Extensions.Logging/LayoutRenderers/MicrosoftConsoleLayoutRenderer.cs
src/NLog.Extensions.Logging/Layouts/MicrosoftConsoleJsonLayout.cs
test/NLog.Extensions.Logging.Tests/MicrosoftConsoleJsonLayoutTests.cs
test/NLog.Extensions.Logging.Tests/MicrosoftConsoleLayoutRendererTest.cs

Can be used like this:
```xml
<target type="file" name="logfile">
<layout type="MicrosoftConsoleJsonLayout" includeScopes="true" />
</target>
```
And generates this output:
```json
{
"EventId": 110,
"LogLevel": "Debug",
"Category": "ConsoleApp.Program",
"Message": "M1 System.Exception: Third time's the charm. System.Exception: This is the second error.",
"State": {
"Message": "M1 System.Exception: Third time's the charm. System.Exception: This is the second error.",
"ex2": "System.Exception: This is the second error.",
"ex3": "System.Exception: Third time's the charm.",
"{OriginalFormat}": "M1 {ex3} {ex2}"
}
}
```

MicrosoftConsoleJsonLayout - Simulates Microsoft AddJsonConsole Formatter

---

appveyor.yml
test/NLog.Extensions.Logging.Tests/ConfigSettingLayoutRendererTests.cs
test/NLog.Extensions.Logging.Tests/Extensions/ConfigureExtensionsTests.cs
test/NLog.Extensions.Logging.Tests/NLog.Extensions.Logging.Tests.csproj
test/NLog.Extensions.Logging.Tests/NLogLoggingConfigurationTests.cs

Removed netcoreapp1.1 since reached end-of-life.

Bump  to Visual Studio 2022 on AppVeyor + Removed .NET core 1 tests 

---

src/NLog.Extensions.Logging/LayoutRenderers/MicrosoftConsoleLayoutRenderer.cs
src/NLog.Extensions.Logging/Layouts/MicrosoftConsoleJsonLayout.cs
src/NLog.Extensions.Logging/Logging/EventIdCaptureType.cs
src/NLog.Extensions.Logging/Logging/NLogLogger.cs
src/NLog.Extensions.Logging/Logging/NLogProviderOptions.cs
test/NLog.Extensions.Logging.Tests/Extensions/ConfigureExtensionsTests.cs
test/NLog.Extensions.Logging.Tests/nlog.config

Resolves #553
Follow up to #319  and  #538

NLogProviderOptions with support for CaptureEventId.EventId + EventName

---

src/NLog.Extensions.Hosting/Extensions/ConfigureExtensions.cs

See also: https://github.com/NLog/NLog.Web/pull/691

NLogProviderOptions ShutdownOnDispose = true disables LogFactory.AutoShutdown

---

src/NLog.Extensions.Logging/LayoutRenderers/MicrosoftConsoleLayoutRenderer.cs
test/NLog.Extensions.Logging.Tests/MicrosoftConsoleLayoutRendererTest.cs

When an EventID comes in to the MicrosoftConsoleLayout formatter, if the ID is not within the range of pre-mapped event IDs (currently 0 to 50), then it should be simply converted to a string.
See #569 for details on original issue

Ensure event ID out of mapper range is parsed

---

src/NLog.Extensions.Logging/LayoutRenderers/MicrosoftConsoleLayoutRenderer.cs

StringBuilder in .NET5 (and newer) can append integer without string-allocation (using span)

MicrosoftConsoleLayoutRenderer - Skip string-allocation for EventId when possible on platform

---

src/NLog.Extensions.Hosting/Extensions/ConfigureExtensions.cs
src/NLog.Extensions.Logging/Extensions/ConfigureExtensions.cs
src/NLog.Extensions.Logging/Internal/RegisterNLogLoggingProvider.cs
src/NLog.Extensions.Logging/Logging/NLogProviderOptions.cs
test/NLog.Extensions.Logging.Tests/Extensions/ConfigureExtensionsTests.cs

For better support of setting RemoveLoggerFactoryFilter and ReplaceLoggerFactory in appsettings.json. Resolves #578

Configure NLogProviderOptions from HostBuilder Configuration

---

src/NLog.Extensions.Hosting/Extensions/ConfigureExtensions.cs
src/NLog.Extensions.Logging/Extensions/ConfigureExtensions.cs
src/NLog.Extensions.Logging/Internal/RegisterNLogLoggingProvider.cs

Configure NLogProviderOptions from HostBuilder Configuration (code style)

---

src/NLog.Extensions.Logging/Logging/NLogBeginScopeParser.cs
test/NLog.Extensions.Logging.Tests/LoggerTests.cs

See also: https://stackoverflow.com/questions/71734962/net-core-6-nlog-and-ilogger-log-to-sql-server-database-custom-fields-issue/71756335#71756335

NLogBeginScopeParser - Improve parsing of custom KeyValuePair as scope-properties

---

src/NLog.Extensions.Logging/Layouts/MicrosoftConsoleJsonLayout.cs

- https://docs.microsoft.com/dotnet/api/microsoft.extensions.logging.consoleloggerextensions.addjsonconsole

Fix typo in xml-docs for MicrosoftConsoleJsonLayout

---

src/NLog.Extensions.Logging/LayoutRenderers/ConfigSettingLayoutRenderer.cs
test/NLog.Extensions.Logging.Tests/ConfigSettingLayoutRendererTests.cs

```json
"Logging": {
"LogLevel": {
"Default": "Error",
"Microsoft": "Information",
"Microsoft.Hosting.Lifetime": "Error"
}
```
Can now resolved like this:
```
${configsetting:item=Logging.Microsoft\.Hosting\.Lifetime}
```

ConfigSettingLayoutRenderer - Support escape of dot-separator

---

src/NLog.Extensions.Logging/Config/SetupBuilderExtensions.cs

Should be possible to load configuration from external source without affecting configsetting-lookup

Removed RegisterConfigSettings from LoadConfigurationFromSection

---

src/NLog.Extensions.Logging/Config/SetupBuilderExtensions.cs
src/NLog.Extensions.Logging/Config/SetupExtensionsBuilderExtensions.cs

Follow up to #626 (Ensure extension-types are registered, before loading config, and allow config assign when unassigned)

LoadConfigurationFromSection should RegisterConfigSettings without configuration assign

---

src/NLog.Extensions.Logging/Logging/NLogLogger.cs
src/NLog.Extensions.Logging/Logging/NLogMessageParameterList.cs
test/NLog.Extensions.Logging.Tests/Logging/NLogMessageParameterListTests.cs
test/NLog.Extensions.Logging.Tests/NLogMessageParameterListTests.cs

Skips capture of `LogEventInfo.Parameters`-array

NLogMessageParameterList - Skip property parsing when simple positional message template

---

src/NLog.Extensions.Hosting/Extensions/ConfigureExtensions.cs
src/NLog.Extensions.Hosting/NLog.Extensions.Hosting.csproj
src/NLog.Extensions.Logging/Config/NLogLoggingConfiguration.cs
src/NLog.Extensions.Logging/Extensions/ConfigureExtensions.cs
src/NLog.Extensions.Logging/Internal/Guard.cs
src/NLog.Extensions.Logging/Internal/RegisterNLogLoggingProvider.cs
src/NLog.Extensions.Logging/Logging/NLogBeginScopeParser.cs
src/NLog.Extensions.Logging/Logging/NLogLogger.cs
test/NLog.Extensions.Hosting.Tests/ExtensionMethodTests.cs
test/NLog.Extensions.Logging.Tests/CustomBeginScopeTest.cs
test/NLog.Extensions.Logging.Tests/Extensions/ConfigureExtensionsTests.cs
test/NLog.Extensions.Logging.Tests/NLogTestBase.cs

Added Guard.ThrowIfNull to throw ArgumentNullException, better than NRE

---

src/NLog.Extensions.Logging/Config/NLogLoggingConfiguration.cs
test/NLog.Extensions.Logging.Tests/NLogLoggingConfigurationTests.cs

Fixed NLogLoggingConfiguration to handle wrapped targets without name

---

CHANGELOG.MD
build.ps1
src/NLog.Extensions.Logging/NLog.Extensions.Logging.csproj

Update to NLog v5.1.2 - https://github.com/NLog/NLog/releases/tag/v5.1.2

Version 5.2.2

---

src/NLog.Extensions.Logging/Logging/NLogBeginScopeParser.cs
test/NLog.Extensions.Logging.Tests/CustomBeginScopeTest.cs
test/NLog.Extensions.Logging.Tests/Extensions/ConfigureExtensionsTests.cs

NLog v5.1.3 now ignores `null` when used as nested-state in `ScopeContext.PushNestedStateProperties`.

NLogBeginScopeParser - Skip capture of nested state when List + Array + Dictionary

---

src/NLog.Extensions.Hosting/NLog.Extensions.Hosting.csproj
src/NLog.Extensions.Hosting/README.md
src/NLog.Extensions.Logging/NLog.Extensions.Logging.csproj
src/NLog.Extensions.Logging/README.md

Added README.md for the nuget-package

---

examples/NetCore2/HostingExample/HostingExample.csproj
run-tests.ps1
src/NLog.Extensions.Hosting/NLog.Extensions.Hosting.csproj
src/NLog.Extensions.Logging/Config/SetupExtensionsBuilderExtensions.cs
src/NLog.Extensions.Logging/Extensions/ConfigureExtensions.cs
src/NLog.Extensions.Logging/LayoutRenderers/ConfigSettingLayoutRenderer.cs
src/NLog.Extensions.Logging/LayoutRenderers/MicrosoftConsoleLayoutRenderer.cs
src/NLog.Extensions.Logging/Layouts/MicrosoftConsoleJsonLayout.cs
src/NLog.Extensions.Logging/Logging/NLogBeginScopeParser.cs
src/NLog.Extensions.Logging/Logging/NLogLogger.cs
src/NLog.Extensions.Logging/Logging/NLogLoggerProvider.cs
src/NLog.Extensions.Logging/NLog.Extensions.Logging.csproj
src/NLog.Extensions.Logging/Targets/MicrosoftILoggerTarget.cs
test/NLog.Extensions.Hosting.Tests/ExtensionMethodTests.cs
test/NLog.Extensions.Logging.Tests/ApiTests.cs
test/NLog.Extensions.Logging.Tests/LoggerTests.cs
test/NLog.Extensions.Logging.Tests/NLogTestBase.cs

- Update to NLog 5.2 - https://github.com/NLog/NLog/releases/tag/v5.2.0

NLogLoggerProvider - Replaced dynamic assembly loading with registration methods

---

CHANGELOG.MD
build.ps1
src/NLog.Extensions.Logging/Logging/NLogLogger.cs
src/NLog.Extensions.Logging/Logging/NLogMessageParameterList.cs
src/NLog.Extensions.Logging/Logging/NLogProviderOptions.cs
src/NLog.Extensions.Logging/NLog.Extensions.Logging.csproj
test/NLog.Extensions.Hosting.Tests/NLog.Extensions.Hosting.Tests.csproj
test/NLog.Extensions.Logging.Tests/LoggerTests.cs
test/NLog.Extensions.Logging.Tests/NLog.Extensions.Logging.Tests.csproj
test/NLog.Extensions.Logging.Tests/NLogMessageParameterListTests.cs

Introduced CaptureMessageParameters to skip allocating Parameters-array

---

src/NLog.Extensions.Logging/Logging/NLogLoggerFactory.cs

See also: https://devblogs.microsoft.com/dotnet/performance-improvements-in-net-8/#logging

NLogLoggerFactory - Optimize concurrency for CreateLogger

---

CHANGELOG.MD
build.ps1
src/NLog.Extensions.Logging/NLog.Extensions.Logging.csproj

**NLog Version 5.2.7 (2023/11/28)**
- [#5427](https://redirect.github.com/NLog/NLog/pull/5427) FileTarget - Fix Windows FileSystem Tunneling when KeepFileOpen=false ([#5427](https://redirect.github.com/NLog/NLog/issues/5427)) ([@​snakefoot](https://github.com/snakefoot))
- [#5422](https://redirect.github.com/NLog/NLog/pull/5422) AppEnvironmentWrapper - Added Entry-Assembly as fallback for ProcessName ([#5422](https://redirect.github.com/NLog/NLog/issues/5422)) ([@​snakefoot](https://github.com/snakefoot))
- [#5419](https://redirect.github.com/NLog/NLog/pull/5419) Improved XML docs for MDC, MDLC, NDC, NDLC about being replaced by ScopeContext ([#5419](https://redirect.github.com/NLog/NLog/issues/5419)) ([@​snakefoot](https://github.com/snakefoot))
**NLog Version 5.2.6 (2023/11/19)**
- …

Version 5.3.7

---

src/NLog.Extensions.Logging/Config/NLogLoggingConfiguration.cs
src/NLog.Extensions.Logging/README.md
test/NLog.Extensions.Logging.Tests/NLogLoggingConfigurationTests.cs

Auto ordering of variables-section when dependent variables

---

src/NLog.Extensions.Hosting/NLog.Extensions.Hosting.csproj
src/NLog.Extensions.Logging/NLog.Extensions.Logging.csproj

Added Copyright to nuget-package

---

examples/NetCore2/HostingExample/HostingExample.csproj
src/NLog.Extensions.Logging/Logging/NLogMessageParameterList.cs
test/NLog.Extensions.Hosting.Tests/NLog.Extensions.Hosting.Tests.csproj

Skip check of `CaptureType` when not having MessageTemplateCapture.

NLogMessageParameterList - Optimize check of CaptureType for index operator 

---

src/NLog.Extensions.Logging/Logging/NLogLogger.cs
src/NLog.Extensions.Logging/Logging/NLogMessageParameterList.cs
test/NLog.Extensions.Logging.Tests/LoggerTests.cs
test/NLog.Extensions.Logging.Tests/NLogMessageParameterListTests.cs

NLog expects message-template to be either positional or structured, and will complain when mixing.
Microsoft Logging Formatter treats all message-templates as structured-format (Not correctly support the positional format)

Fallback to Microsoft Logging Formatter when mixing positional with structured

---

test/NLog.Extensions.Logging.Tests/LoggerTests.cs

Fallback to Microsoft Logging Formatter when mixing positional with structured (test coverage)

---

src/NLog.Extensions.Logging/Config/NLogLoggingConfiguration.cs
src/NLog.Extensions.Logging/NLog.Extensions.Logging.csproj
test/NLog.Extensions.Hosting.Tests/NLog.Extensions.Hosting.Tests.csproj
test/NLog.Extensions.Logging.Tests/NLog.Extensions.Logging.Tests.csproj
test/NLog.Extensions.Logging.Tests/NLogLoggingConfigurationTests.cs

Trying to resolve #759 by avoiding double-registration on the config-changed-event.

NLogLoggingConfiguration - Fix memory-leak when using AutoReload

---

src/NLog.Extensions.Hosting/Extensions/ConfigureExtensions.cs

Use `LoadConfigurationFromFile` instead of explicit creating `XmlLoggingConfiguration` for better NLog InternalLogger output.

UseNLog allow fallback to only EnvironmentName for NLog config

---

src/NLog.Extensions.Logging/Layouts/MicrosoftConsoleJsonLayout.cs

NLog v5.3.4 optimized DateLayoutRenderer when using `Format=o`

MicrosoftConsoleJsonLayout - TimestampLayout replaced by DateLayoutRenderer

---

src/NLog.Extensions.Logging/Layouts/MicrosoftConsoleJsonLayout.cs
test/NLog.Extensions.Logging.Tests/MicrosoftConsoleJsonLayoutTests.cs

Skip verification of characters that must be json-encoded for TimeStamp and LogLevel for better performance.

MicrosoftConsoleJsonLayout - Skip Encode for Timestamp and LogLevel

---

CHANGELOG.MD
appveyor.yml
build.ps1
src/NLog.Extensions.Logging/Logging/NLogLoggerFactory.cs
src/NLog.Extensions.Logging/NLog.Extensions.Logging.csproj

- NLog v5.4 - https://github.com/NLog/NLog/releases/tag/v5.4.0

Version 5.4

---

CHANGELOG.MD
build.ps1
examples/NetCore2/ConsoleExample/nlog.config
examples/NetCore2/HostingExample/nlog.config
src/NLog.Extensions.Hosting/Extensions/ConfigureExtensions.cs
src/NLog.Extensions.Hosting/ILLink.Descriptors.xml
src/NLog.Extensions.Hosting/NLog.Extensions.Hosting.csproj
src/NLog.Extensions.Logging/Config/NLogLoggingConfiguration.cs
src/NLog.Extensions.Logging/Config/SetupExtensionsBuilderExtensions.cs
src/NLog.Extensions.Logging/Extensions/ConfigureExtensions.cs
src/NLog.Extensions.Logging/ILLink.Descriptors.xml
src/NLog.Extensions.Logging/Internal/RegisterNLogLoggingProvider.cs
src/NLog.Extensions.Logging/LayoutRenderers/ConfigSettingLayoutRenderer.cs
src/NLog.Extensions.Logging/LayoutRenderers/MicrosoftConsoleLayoutRenderer.cs
src/NLog.Extensions.Logging/Layouts/MicrosoftConsoleJsonLayout.cs
src/NLog.Extensions.Logging/Logging/NLogBeginScopeParser.cs
src/NLog.Extensions.Logging/Logging/NLogLogger.cs
src/NLog.Extensions.Logging/Logging/NLogLoggerProvider.cs
src/NLog.Extensions.Logging/Logging/NLogMessageParameterList.cs
src/NLog.Extensions.Logging/NLog.Extensions.Logging.csproj
src/NLog.Extensions.Logging/Targets/MicrosoftILoggerTarget.cs
test/NLog.Extensions.Hosting.Tests/NLog.Extensions.Hosting.Tests.csproj
test/NLog.Extensions.Logging.Tests/ApiTests.cs
test/NLog.Extensions.Logging.Tests/Extensions/ConfigureExtensionsTests.cs
test/NLog.Extensions.Logging.Tests/MicrosoftILoggerTargetTests.cs
test/NLog.Extensions.Logging.Tests/NLog.Extensions.Logging.Tests.csproj
test/NLog.Extensions.Logging.Tests/NLogLoggingConfigurationTests.cs

Upgrade to NLog v6.0 RC2 and updated to use nullable references.
Resolves #540

NLog v6 RC2

---

appveyor.yml
src/NLog.Extensions.Hosting/Extensions/ConfigureExtensions.cs
test/NLog.Extensions.Hosting.Tests/ExtensionMethodTests.cs

NET Framework v4.6.2 with UseNLog for IHostApplicationBuilder
