NLog/NLog.Extensions.Logging

appveyor.yml

dnu install

---

src/NLog.Framework.logging/AspNetExtensions.cs

Described at
https://github.com/NLog/NLog/issues/641#issuecomment-180731577

Fix path in ConfigureNLog

---

appveyor.yml

wouldn't describe it as quiet... 
from almost 1200 build lines to 600

quiet restore

---

examples/aspnet-core-example/src/aspnet-core-example/Controllers/HomeController.cs
examples/aspnet-core-example/src/aspnet-core-example/Controllers/ValuesController.cs
examples/aspnet-core-example/src/aspnet-core-example/project.json

Includes nlog.config in publish output.
Removes LogManager dependency.

Example update

---

global.json
src/NLog.Extensions.Logging/project.json

RC2 -> RTM

---

src/NLog.Extensions.Logging/AspNetExtensions.cs

fixes https://github.com/NLog/NLog.Extensions.Logging/issues/43, fixes https://github.com/NLog/NLog.Extensions.Logging/issues/50

Fix retrieving the root of content folder

---

src/NLog.Extensions.Logging/project.json

Fixes https://github.com/NLog/NLog.Extensions.Logging/issues/52
changes without whitespace: https://github.com/NLog/NLog.Extensions.Logging/pull/57/files?w=1

Fix frameworkAssemblies for net(4.6.1)

---

src/NLog.Extensions.Logging/AspNetExtensions.cs

Filter Microsoft.Extensions.Logging.Filter if used
fixes https://github.com/NLog/NLog.Extensions.Logging/issues/67

Improve ${callsite} when filtering is used.

---

src/NLog.Extensions.Logging/NLogLogger.cs

related https://github.com/NLog/NLog.Extensions.Logging/issues/78

Update XML docs for BeginScope

---

global.json
src/NLog.Extensions.Logging/ConfigureExtensions.cs
src/NLog.Extensions.Logging/project.json

supersedes https://github.com/NLog/NLog.Extensions.Logging/pull/37
depended of https://github.com/NLog/NLog.Extensions.Logging/pull/82

Allow chaining in config

---

src/NLog.Extensions.Logging/project.json

Fixes https://github.com/NLog/NLog.Extensions.Logging/issues/91

Fix installation issues on .NET 4.6+

---

src/NLog.Extensions.Logging/NLog.Extensions.Logging.csproj
src/NLog.Extensions.Logging/NLogLogger.cs
test/LoggerTests.cs

Log exceptions when log message empty

---

src/NLog.Extensions.Logging/ConfigureExtensions.cs
src/NLog.Extensions.Logging/NLog.Extensions.Logging.csproj
src/NLog.Extensions.Logging/NLogLogger.cs
test/NLog.Extensions.Logging.Tests.csproj

ILoggerFactory & rename parameters
fixes #108 
related https://github.com/NLog/NLog.Web/issues/172

.NET Standard 2 support 

---

src/NLog.Extensions.Logging/NLog.Extensions.Logging.csproj

note: this for .net core 2,
asp.net core 2 needs an update in nlog.web.aspnetcore

1.0.0-rtm-beta6: Changelog and version

---

src/NLog.Extensions.Logging/NLog.Extensions.Logging.csproj
src/NLog.Extensions.Logging/NLogLoggerProvider.cs
src/NLog.Extensions.Logging/NLogProviderOptions.cs

fixes https://github.com/NLog/NLog.Extensions.Logging/issues/139

Enable XML docs + docs

---

.travis.yml
build.sh

Enabled Travis build

---

src/NLog.Extensions.Logging/NLog.Extensions.Logging.csproj

Update dependencies version range

---

src/NLog.Extensions.Logging/ConfigureExtensions.cs

ignore assemblies - prevent assembly.load
fixes https://github.com/NLog/NLog.Extensions.Logging/issues/156

Fix Recursive resource lookup bug

---

src/NLog.Extensions.Logging/ConfigureExtensions.cs

Fixes https://github.com/NLog/NLog.Extensions.Logging/issues/165
or at least better logging

Fix callsite

---

src/NLog.Extensions.Logging/NLog.Extensions.Logging.csproj
test/NLog.Extensions.Logging.Tests.csproj

Fixed dependencies to support NetCoreApp10, and resolves #91

Removed System.Runtime for net451

---

src/NLog.Extensions.Logging/Extensions/ConfigureExtensions.cs

Example of how to resolve  #191 (When https://github.com/NLog/NLog/pull/2519 has been merged)

Using LogManager.LoadConfiguration

---

src/NLog.Extensions.Logging/Logging/NLogLogger.cs
src/NLog.Extensions.Logging/Logging/NLogMessageParameterList.cs
test/LoggerTests.cs

MessageProperties - Support list with single property

---

src/NLog.Extensions.Logging/Extensions/ConfigureExtensions.cs
src/NLog.Extensions.Logging/NLog.Extensions.Logging.csproj

Net451 doesn't need explicit manual help (NLog does it automatically)

ConfigureHiddenAssemblies only needed for NetCoreApp1

---

examples/NetCore2/ConsoleExample/Program.cs

Resolves #201
Also updated Wiki: https://github.com/NLog/NLog.Extensions.Logging/wiki/Getting-started-with-.NET-Core-2---Console-application

Update NetCore2 ConsoleExample with LogManager.Shutdown

---

appveyor.yml
run-sonar.ps1
src/NLog.Extensions.Logging/NLog.Extensions.Logging.csproj

Enable sonar analysis
important in AppVeyor:

Added Sonar

---

src/NLog.Extensions.Logging/NLog.Extensions.Logging.csproj

fixes https://github.com/NLog/NLog.Extensions.Logging/issues/216, thanks @aweebs!

Update NLog dependency, exclude NLog 5 pre-releases

---

CHANGELOG.MD
build.ps1
src/NLog.Extensions.Logging/NLog.Extensions.Logging.csproj

Release 1.0.2

---

CHANGELOG.MD
appveyor.yml
build.ps1
src/NLog.Extensions.Logging/NLog.Extensions.Logging.csproj

Updated NLog version, release 1.1

---

CHANGELOG.MD
build.ps1
src/NLog.Extensions.Logging/NLog.Extensions.Logging.csproj

Version 1.2

---

CHANGELOG.MD
build.ps1
src/NLog.Extensions.Logging/NLog.Extensions.Logging.csproj

Version 1.2.1

---

NLog.Extensions.Logging.sln
appveyor.yml
build.ps1

Create snupkg packages

---

CHANGELOG.MD
src/NLog.Extensions.Hosting/Extensions/ConfigureExtensions.cs
src/NLog.Extensions.Hosting/NLog.Extensions.Hosting.csproj
src/NLog.Extensions.Logging/NLog.Extensions.Logging.csproj

Version 1.4 release notes

---

appveyor.yml

Deploy snupkg on AppVeyor

---

appveyor.yml

Should work without hassle: https://github.com/appveyor/ci/issues/2753#issuecomment-494656131

Deploy snupkg on AppVeyor natively

---

test/NLog.Extensions.Logging.Tests/MicrosoftILoggerTargetTests.cs
test/NLog.Extensions.Logging.Tests/NLog.Extensions.Logging.Tests.csproj

pure refactoring, not new or changed tests

refactor tests

---

test/NLog.Extensions.Logging.Tests/Extensions/ConfigureExtensionsTests.cs

Just some task to make the most of the waiting in the plane 😄

Improved test Coverage

---

test/NLog.Extensions.Logging.Tests/Logging/NLogLoggerFactoryTests.cs
test/NLog.Extensions.Logging.Tests/Logging/NLogLoggerProviderTests.cs
test/NLog.Extensions.Logging.Tests/NLogTestBase.cs

Don't run tests with internal log in parallel

---

src/NLog.Extensions.Logging/Extensions/ConfigureExtensions.cs
test/NLog.Extensions.Logging.Tests/Extensions/ConfigureExtensionsTests.cs

Prepare for fluent-methods that one day will come for LogFactory for building NLog-config.

Added AddNLog with functor to create/initialize LogFactory for NLogLoggingProvider

---

src/NLog.Extensions.Hosting/NLog.Extensions.Hosting.csproj
src/NLog.Extensions.Logging/NLog.Extensions.Logging.csproj

related https://github.com/NLog/NLog.Web/pull/616/

Move to PackageIcon and PackageLicenseExpression for NuGet package

---

src/NLog.Extensions.Hosting/NLog.Extensions.Hosting.csproj
src/NLog.Extensions.Logging/NLog.Extensions.Logging.csproj

Minor adjustment of nuget-description.

Update nuget-description with ASP.NET Core so it matches NLog-nuget

---

src/NLog.Extensions.Logging/Targets/MicrosoftILoggerTarget.cs

Reduce chance of congestion and deadlock in ILoggerFactory

MicrosoftILoggerTarget - Added caching of created Loggers

---

src/NLog.Extensions.Logging/Config/SetupBuilderExtensions.cs
src/NLog.Extensions.Logging/Internal/RegisterNLogLoggingProvider.cs

NLogProviderOptions - Use LogFactory from provider when using LoggingConfigurationSectionName

---

CHANGELOG.MD
appveyor.yml
build.ps1
src/NLog.Extensions.Hosting/NLog.Extensions.Hosting.csproj
src/NLog.Extensions.Logging/NLog.Extensions.Logging.csproj

Version 5.0 preview 1

---

build.ps1
src/NLog.Extensions.Hosting/NLog.Extensions.Hosting.csproj
src/NLog.Extensions.Logging/NLog.Extensions.Logging.csproj

Prepare for https://github.com/NLog/NLog.Web/issues/684

Changed from netcoreapp3.0 to netcoreapp3.1

---

src/NLog.Extensions.Logging/Logging/NLogBeginScopeParser.cs
src/NLog.Extensions.Logging/Logging/NLogProviderOptions.cs
test/NLog.Extensions.Logging.Tests/Extensions/ConfigureExtensionsTests.cs

Fixed spelling for IncludeActivityIdsWithBeginScope

---

src/NLog.Extensions.Hosting/Extensions/ConfigureExtensions.cs

Loading NLog.config from contentRootPath as last fallback (Fix Sonar)

---

src/NLog.Extensions.Hosting/Extensions/ConfigureExtensions.cs
src/NLog.Extensions.Logging/Config/SetupExtensionsBuilderExtensions.cs
src/NLog.Extensions.Logging/Extensions/ConfigureExtensions.cs
src/NLog.Extensions.Logging/Internal/RegisterNLogLoggingProvider.cs

Now using RegisterLayout from https://github.com/NLog/NLog/pull/5078

NLog.Extensions.Hosting - Skip RegisterItemsFromAssembly since handled by RegisterConfigSettings

---

documentation/gettingstarted.md

Removed gettingstarted.md

---

src/NLog.Extensions.Hosting/README.md
src/NLog.Extensions.Logging/README.md

Added README.md for the nuget-package - Fix links

---

CHANGELOG.MD
build.ps1
src/NLog.Extensions.Logging/NLog.Extensions.Logging.csproj

- NLog v5.2.1 - https://github.com/NLog/NLog/releases/tag/v5.2.1

Version 5.3.1

---

CHANGELOG.MD
build.ps1
src/NLog.Extensions.Logging/NLog.Extensions.Logging.csproj

- NLog v5.2.2 - https://github.com/NLog/NLog/releases/tag/v5.2.2

Version 5.3.2

---

CHANGELOG.MD
appveyor.yml
build.ps1
src/NLog.Extensions.Logging/NLog.Extensions.Logging.csproj

- NLog v5.2.5 - https://github.com/NLog/NLog/releases/tag/v5.2.5

Version 5.3.5

---

build.ps1
examples/NetCore2/HostingExample/HostingExample.csproj
run-tests.ps1
src/NLog.Extensions.Hosting/NLog.Extensions.Hosting.csproj
src/NLog.Extensions.Logging/NLog.Extensions.Logging.csproj

-  [x] Waiting for AppVeyor to upgrade their VS2022 Image.

Explicit support for NET8

---

src/NLog.Extensions.Logging/Config/NLogLoggingConfiguration.cs
test/NLog.Extensions.Logging.Tests/NLogLoggingConfigurationTests.cs

Followup to #737 (Always yield complex variables as last items)

Auto ordering of variables-section when dependent complex variables

---

src/NLog.Extensions.Logging/Config/NLogLoggingConfiguration.cs
test/NLog.Extensions.Logging.Tests/NLogLoggingConfigurationTests.cs

Fix Auto ordering of variables-section when dependent variables

---

CHANGELOG.MD
build.ps1
src/NLog.Extensions.Logging/NLog.Extensions.Logging.csproj

- NLog v5.3.2 - https://github.com/NLog/NLog/releases/tag/v5.3.2

Version 5.3.10

---

CHANGELOG.MD
appveyor.yml
build.ps1
src/NLog.Extensions.Logging/NLog.Extensions.Logging.csproj

- https://github.com/NLog/NLog.Extensions.Logging/releases/tag/v5.3.14

Version 5.3.14

---

src/NLog.Extensions.Hosting/Extensions/ConfigureExtensions.cs
test/NLog.Extensions.Hosting.Tests/ExtensionMethodTests.cs

UseNLog with support for isolated LogFactory

---

CHANGELOG.MD
build.ps1
src/NLog.Extensions.Logging/NLog.Extensions.Logging.csproj
test/NLog.Extensions.Hosting.Tests/NLog.Extensions.Hosting.Tests.csproj
test/NLog.Extensions.Logging.Tests/NLog.Extensions.Logging.Tests.csproj

NLog v6 RC3

---

CHANGELOG.MD
README.md
appveyor.yml
build.ps1
src/NLog.Extensions.Logging/NLog.Extensions.Logging.csproj

- https://github.com/NLog/NLog/releases/tag/v6.0.1

Version 6.0.1

---

CHANGELOG.MD
build.ps1
src/NLog.Extensions.Logging/NLog.Extensions.Logging.csproj

- https://github.com/NLog/NLog/releases/tag/v6.0.3

Version 6.0.3
